version: '3.7'

networks:
  default:
    name: chat_app_network
    driver: bridge
    ipam:
      config:
        - subnet: 160.170.100.0/24

services:
  keycloak:
    user: root
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    restart: unless-stopped
    ports:
      - '7070:8080'
    depends_on:
      - postgres
    env_file:
      - ./keycloak/keycloak.env
    command: -b 0.0.0.0 -bmanagement 0.0.0.0

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    env_file:
      - ./postgres/postgres.env

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  cassandra:
    user: root
    image: bitnami/cassandra:4.0.3
    container_name: casandra
    restart: unless-stopped
    ports:
      - '9042:9042'
    volumes:
      - ./casandra/data:/bitnami

  rabbitmq-stomp:
    image: onedatateam/rabbitmq-stomp:latest
    container_name: rabbitmq-stomp
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'

  discovery:
    image: steeltoeoss/eureka-server
    container_name: discovery
    restart: unless-stopped
    ports:
      - '8761:8761'